# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Add Secure Code Warrior contextual training to SARIF
        # You may pin to the exact commit or the version.
        # uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@944233043877d9b1efd95ce296623db960e45970
        uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1.0.6
        with:
          # Relative location of SARIF file(s) to process
          inputSarifFile: ./findings.sarif
          # Relative destination location for processed SARIF file(s)
          outputSarifFile: ./findings.processed.sarif
          # Provide `secrets.GITHUB_TOKEN` to use the GitHub access token automatically supplied by GitHub Workflows
          #githubToken: # optional
